import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Components/Common/Header";
import Sidebar from "./Components/Common/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Sidebar />
        <main>
          <section className="py-4 px-4 md:px-5 md:pl-[270px] pt-[85px] min-h-[100vh]">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
